### ISSUE TITLE
Plugin stops giving suggestions or becomes slower than typing speed after some use

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/plugin-vscode#160] opened 2021-01-22 03:20 UTC
**Description:**
When using VSCode plugin continuously, it stops giving suggestions or becomes slower than typing speed after some use. Restarting the VSCode helps get the suggestions back.

**Comment by riyafa** [comment] 2021-01-22 10:54
This happens during continuous use. Please find attached the project I have been working on
[rest-service.zip](https://github.com/ballerina-platform/plugin-vscode/files/5855298/rest-service.zip)

**Comment by prabushi** [comment] 2021-02-15 04:25
The following errors are logged in the ballerina-internal.log, which are suspected to be the cause of this issue.

```
[2021-01-22 07:49:01,305] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinax.azurefunctions.Utils.extractAzureFuncsPackageSymbol(Utils.java:102)
	at org.ballerinax.azurefunctions.AzureFunctionsPlugin.process(AzureFunctionsPlugin.java:74)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.executePluginSafely(CompilerPluginRunner.java:169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:146)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:134)
	at io.ballerina.projects.internal.CompilerPhaseRunner.annotationProcess(CompilerPhaseRunner.java:245)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:150)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:348)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:297)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:141)
	at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:100)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.getLatestDiagnostics(DiagnosticsHelper.java:116)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.compileAndSendDiagnostics(DiagnosticsHelper.java:80)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:487)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
[2021-01-22 07:49:01,329] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinax.docker.DockerPlugin.lambda$process$0(DockerPlugin.java:101)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.ballerinax.docker.DockerPlugin.process(DockerPlugin.java:102)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.executePluginSafely(CompilerPluginRunner.java:169)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:146)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:163)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:134)
	at io.ballerina.projects.internal.CompilerPhaseRunner.annotationProcess(CompilerPhaseRunner.java:245)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performTypeCheckPhases(CompilerPhaseRunner.java:150)
	at io.ballerina.projects.ModuleContext.compileInternal(ModuleContext.java:348)
	at io.ballerina.projects.ModuleCompilationState$1.compile(ModuleCompilationState.java:45)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:297)
	at io.ballerina.projects.PackageCompilation.compile(PackageCompilation.java:141)
	at io.ballerina.projects.PackageCompilation.diagnosticResult(PackageCompilation.java:100)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.getLatestDiagnostics(DiagnosticsHelper.java:116)
	at org.ballerinalang.langserver.diagnostic.DiagnosticsHelper.compileAndSendDiagnostics(DiagnosticsHelper.java:80)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.didChange(BallerinaTextDocumentService.java:487)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by prabushi** [comment] 2021-02-15 08:31
This should be fixed from the lang side, and it'll be tracked with https://github.com/ballerina-platform/ballerina-lang/issues/28398

**Closed by prabushi** 2021-02-15 08:31 UTC
Labels: Area/AutoCompletion, Area/VSCodeExtension, Type/Bug
